apiVersion: v1
data:
  reverseproxy.conf: "server {\n    listen       80;\n    server_name  localhost;\n\n
    \   location /one {\n        proxy_bind 127.0.0.1;\n        proxy_pass http://127.0.0.1:3000;\n
    \   }\n\tlocation /emp {\n            proxy_bind 127.0.0.1;\n            proxy_pass
    http://127.0.0.1:8080;\n        }\n\n    error_page   500 502 503 504  /50x.html;\n
    \   location = /50x.html {\n        root   /usr/share/nginx/html;\n    }\n}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
